# Generated by Django 4.2.1 on 2023-06-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="khaled", max_length=255),
            preserve_default=False,
        ),
    ]
