# Generated by Django 4.2.1 on 2023-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price_per_ton", models.FloatField(blank=True, null=True)),
                ("shipping_price", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
