# Generated by Django 3.1.7 on 2022-02-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cumulative_deliveries', models.FloatField(blank=True, null=True)),
                ('paied_ammounts', models.FloatField(blank=True, null=True)),
                ('pending_ammounts', models.FloatField(blank=True, null=True)),
                ('deducted_ammonunts', models.FloatField(blank=True, null=True)),
                ('num_of_rejected_deliveries', models.IntegerField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
