# Generated by Django 4.0.3 on 2022-03-13 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('cumulative_deliveries', models.FloatField(blank=True, null=True)),
                ('price_per_ton', models.FloatField(blank=True, null=True)),
                ('paied_ammounts', models.FloatField(blank=True, null=True)),
                ('pending_ammounts', models.FloatField(blank=True, null=True)),
                ('deducted_ammonunts', models.FloatField(blank=True, null=True)),
                ('num_of_rejected_deliveries', models.IntegerField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplier_product', to='products.products_table')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
