# Generated by Django 3.1.7 on 2022-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers_table',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
