# Generated by Django 4.2.1 on 2023-06-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="price_per_ton",
            new_name="pending_amount_to_the_supplier",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="shipping_price",
            new_name="shipping_total",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="total",
            new_name="total_paid_to_supplier",
        ),
        migrations.CreateModel(
            name="SupplierBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_date", models.DateField(auto_now_add=True)),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price_per_ton", models.FloatField(blank=True, null=True)),
                ("shipping", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
    ]
