# Generated by Django 4.2.1 on 2023-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "suppliers",
            "0002_rename_price_per_ton_supplier_pending_amount_to_the_supplier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="total_provided_from_supplier",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
