# Generated by Django 3.1.7 on 2022-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_suppliers_table_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers_table',
            name='price_per_ton',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
