# Generated by Django 4.2.1 on 2023-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0004_supplierbatch_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierBatchProxy",
            fields=[],
            options={
                "verbose_name": "Supplier Batch needs info",
                "verbose_name_plural": "Supplier Batches need info",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suppliers.supplierbatch",),
        ),
        migrations.AlterField(
            model_name="supplierbatch",
            name="price_per_ton",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbatch",
            name="shipping",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
