# Generated by Django 4.2.1 on 2023-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "suppliers",
            "0005_supplierbatchproxy_alter_supplierbatch_price_per_ton_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierbatch",
            name="shift",
            field=models.CharField(default="Night", max_length=7),
            preserve_default=False,
        ),
    ]
