# Generated by Django 4.2.1 on 2023-06-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0006_supplierbatch_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierbatch",
            name="price_per_ton",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="supplierbatch",
            name="shipping",
            field=models.FloatField(default=0.0),
        ),
    ]
