# Generated by Django 4.2.1 on 2023-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0008_alter_supplierbatch_price_per_ton_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierbatch",
            name="price_per_ton",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbatch",
            name="shipping",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
