# Generated by Django 4.0.3 on 2022-03-12 20:27

import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, unique=True)),
                ('invoice_number', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_period_start', models.DateField(blank=True, null=True)),
                ('invoice_period_end', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po', to='clients.clients_table')),
            ],
            options={
                'verbose_name_plural': 'POs',
            },
        ),
        migrations.CreateModel(
            name='invoices_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sub_total', models.FloatField()),
                ('item_total', models.FloatField()),
                ('VAT', models.IntegerField(default=14)),
                ('CIT', models.IntegerField(default=1)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tax_reg_num', models.CharField(default='618-665-959', max_length=255)),
                ('CR_number', models.CharField(default='160612', max_length=255)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('bank_info', models.TextField(default='National Bank OF EGYPT \naccount number 6433171331027301011\naccount branch : Merag City Branch \nIBAN : EG 250003064331713310273010110')),
                ('invoice_footer', models.TextField(default='info@alnourrrubber.com  |  +0201100671510  |  +0201000380435')),
                ('address', models.TextField(default='شركه النور للمنتجات المطاطيه\nشارع علي حفظي متفرع من الشارع الجديد التبين حلوان')),
                ('PO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='finance.po_table')),
            ],
            options={
                'verbose_name_plural': 'invoices',
            },
        ),
    ]
