# Generated by Django 4.0.3 on 2022-03-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('alarm_ammount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'expeses categories',
            },
        ),
    ]
