# Generated by Django 4.0.3 on 2022-03-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expenses_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_ammount', models.FloatField()),
                ('description', models.TextField()),
                ('function', models.TextField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_category', to='finance.expenses_category')),
            ],
            options={
                'verbose_name_plural': 'Expeses',
            },
        ),
    ]
