# Generated by Django 4.0.3 on 2022-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='loader_expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('load', models.BooleanField(default=False)),
                ('unload', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Loader Expeses',
            },
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='alarm_ammount',
            new_name='ammount',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='invoice_date',
            new_name='date',
        ),
    ]
