# Generated by Django 4.0.3 on 2022-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_loader_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='ammount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='function',
            field=models.TextField(blank=True, null=True),
        ),
    ]
