# Generated by Django 4.0.3 on 2022-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expenses_ammount_alter_expenses_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
