# Generated by Django 4.0.3 on 2022-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices_table',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
