# Generated by Django 4.0.3 on 2022-03-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_invoices_table_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_table',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
