# Generated by Django 4.0.3 on 2022-03-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_po_table_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_table',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
