# Generated by Django 4.2.1 on 2023-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_report_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionrecord",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rawmaterialrecord",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rawmaterialrecord",
            name="notification_ids",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="soldproductrecord",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
