# Generated by Django 4.2.1 on 2023-06-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "suppliers",
            "0002_rename_price_per_ton_supplier_pending_amount_to_the_supplier_and_more",
        ),
        ("clients", "0001_initial"),
        ("products", "0002_material_type"),
        ("daily_report_api", "0002_alter_productionrecord_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialrecord",
            name="material_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.material_type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productionrecord",
            name="daily_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_records",
                to="daily_report_api.dailyreport",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecord",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="daily_report_api.measurementunit",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecord",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialrecord",
            name="daily_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_material_records",
                to="daily_report_api.dailyreport",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialrecord",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="suppliers.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="soldproductrecord",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="clients.client"
            ),
        ),
        migrations.AlterField(
            model_name="soldproductrecord",
            name="daily_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_product_records",
                to="daily_report_api.dailyreport",
            ),
        ),
        migrations.AlterField(
            model_name="soldproductrecord",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.producttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyreport",
            unique_together={("day", "shift")},
        ),
    ]
