# Generated by Django 4.2.1 on 2023-06-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_report_api", "0003_rawmaterialrecord_material_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterialrecord",
            name="notification_ids",
            field=models.TextField(blank=True, null=True),
        ),
    ]
