# Generated by Django 4.0.3 on 2022-03-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_amount_in_tons', models.IntegerField(blank=True, null=True)),
                ('HQ_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
        ),
    ]
