# Generated by Django 3.1.7 on 2022-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients_table',
            name='add_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
