# Generated by Django 3.1.7 on 2022-02-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_auto_20220204_1140'),
        ('workers', '0004_auto_20220204_1138'),
        ('products', '0002_auto_20220203_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateField(auto_now_add=True)),
                ('price_per_ton', models.FloatField()),
                ('order_max_cap', models.IntegerField(default=0)),
                ('order_pending_ammount', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to='clients.clients_table')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.products_table')),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='packed_rubber_shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('issuer_name', models.CharField(default='AlNour Rubber', max_length=255)),
                ('ammount', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('attestment', models.TextField(blank=True, null=True)),
                ('additional_text', models.TextField(blank=True, null=True)),
                ('additional_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_product', to='products.products_table')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.clients_table')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', to='workers.drivers')),
                ('oreder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dashboard.orders')),
            ],
            options={
                'verbose_name_plural': 'packed rubber shipments',
            },
        ),
    ]
