# Generated by Django 4.0.3 on 2022-03-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shift_types_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'shift types',
            },
        ),
        migrations.CreateModel(
            name='shift_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_type', to='shifts.shift_types_table')),
            ],
            options={
                'verbose_name_plural': 'shift reports',
            },
        ),
    ]
