# Generated by Django 3.1.7 on 2022-02-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_type', to='shifts.shift_types_table')),
            ],
            options={
                'verbose_name_plural': 'shift reports',
            },
        ),
    ]
