# Generated by Django 4.0.3 on 2022-03-13 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'raw_material',
            },
        ),
        migrations.CreateModel(
            name='finished_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.IntegerField()),
                ('weight', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='products.products_table')),
            ],
            options={
                'verbose_name_plural': 'finished_products',
            },
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_ton', models.FloatField()),
                ('weight', models.FloatField()),
                ('penalty', models.FloatField(default=0)),
                ('total_price', models.FloatField()),
                ('loader', models.BooleanField(default=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_suppliers', to='suppliers.suppliers_table')),
            ],
            options={
                'verbose_name_plural': 'Batchs',
            },
        ),
    ]
