# Generated by Django 4.0.3 on 2022-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_raw_material_minimum_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_material',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
