# Generated by Django 4.0.3 on 2022-03-12 20:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('licence', models.CharField(max_length=255)),
                ('number_of_shipments', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('number_of_shifts', models.IntegerField(blank=True, null=True)),
                ('pay_ammount_per_shift', models.FloatField(default=150.0)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('down_payments', models.FloatField(blank=True, null=True)),
                ('deduction', models.FloatField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('upcoming_payment_date', models.DateField(blank=True, null=True)),
                ('shifts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='shifts.shift_types_table')),
            ],
            options={
                'verbose_name_plural': 'workers',
            },
        ),
    ]
