# Generated by Django 3.1.7 on 2022-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('licence', models.CharField(max_length=255)),
                ('number_of_shipments', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('number_of_shifts', models.IntegerField()),
                ('pay_ammount_per_shift', models.FloatField(default=150.0)),
                ('bonus', models.FloatField()),
                ('down_payments', models.FloatField()),
                ('deduction', models.FloatField()),
                ('last_payment_date', models.DateField()),
                ('upcoming_payment_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'drivers',
            },
        ),
    ]
