# Generated by Django 3.1.7 on 2022-02-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='shift_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='shifts.shift_types_table'),
            preserve_default=False,
        ),
    ]
