# Generated by Django 4.0.3 on 2022-03-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='shifts',
        ),
    ]
