# Generated by Django 3.1.7 on 2022-02-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workers_shift_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name_plural': 'workers'},
        ),
    ]
