# Generated by Django 3.1.7 on 2022-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20220203_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='bonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='deduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='down_payments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='number_of_shifts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='upcoming_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
