# Generated by Django 3.1.7 on 2022-02-06 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20220204_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='shifts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), default='{"khaled"}', size=None),
            preserve_default=False,
        ),
    ]
