# Generated by Django 3.1.7 on 2022-02-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products_table',
            options={'verbose_name_plural': 'products'},
        ),
    ]
